// Code generated by Kitex v0.9.1. DO NOT EDIT.

package transportservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	transport "github.com/llsw/ikunnet/kitex_gen/transport"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Call(ctx context.Context, Req *transport.Transport, callOptions ...callopt.Option) (r *transport.Transport, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kTransportServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kTransportServiceClient struct {
	*kClient
}

func (p *kTransportServiceClient) Call(ctx context.Context, Req *transport.Transport, callOptions ...callopt.Option) (r *transport.Transport, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Call(ctx, Req)
}
